= Pitest - demo
:toc:
:toc-placement:

== Introduction

Pitest is a library that helps us do mutation testing, and thus helps us get a measure of the quality of our tests.
It works by randomly seeding variations (aka mutants) in the code that's being tested.
Hence, our tests will run against variants of the code we're intending to test.
If the test fails, the mutation is killed, if it still passes it lives.

Surviving mutations may indicate issues with our test set, since application code changes should lead to different end results and thus to failing tests.

Mutations can take a lot of forms, relational operators being switched around, increments becoming decrements, calls to void methods being removed, ...
A full list be be found on the https://pitest.org/quickstart/mutators/[Pitest Mutator Overview Page]

== Ok, but why?

By default, coverage reports give us information on what code is (not) tested, but no indication on whether our tests are actually able to detect issues properly.
After all, who here hasn't seen a codebase where the tests contain no asserts, yet all branches are executed?

For example, if we generate the jacoco coverage using set1 we'll see that we have a line & branch coverage of 100% magnificent isn't it?
Of course the keen eyed will spot the lack of assertions.


== Notes

* PIT can take a while to run
* Pitest is deterministic, not random

== References

* https://pitest.org/[Official website]
* https://www.arcmutate.com/[Arcmutate] - from the team behind Pitest, offers extra operators
* https://github.com/STAMP-project/pitest-descartes[Descartes] - a mutation plugin engine for PIT implementing extreme mutation operators